### ISSUE TITLE
Add Samples of Direct Composition

### ISSUE THREAD

**Issue by Extrimis** [smourier/DirectN#10]
Hi, I have been having trouble with DirectN when I use with Direct Composition, There is not much place to refer about this, could you add more samples on direct composition. like the example from [here](https://docs.microsoft.com/en-us/archive/msdn-magazine/2014/june/windows-with-c-high-performance-window-layering-using-the-windows-composition-engine).

This sample uses all d3d11, d2d1 and direct composition, it would be helpful, if you could add samples like this.

**Comment by smourier** [comment]
The direct composition as used by Kenny Kerr is interesting for sample code, but with today code, you should use WinRT's Windows.UI.Composition (for which you don't need DirectN).

**Comment by Extrimis** [comment]
i thought adding more samples would help everyone to easily use DirectN, the library is really helpful for beginners, we don't need to worry about pointers and stuff..
