### ISSUE TITLE
IDCompositionFlood Effect is Missing

### ISSUE THREAD

**Issue by Extrimis** [smourier/DirectN#12]
The `IDCompositionFloodEffect `is missing in DirectN, The Microsoft has also removed this from `dcomp.h`, will it be possible to add it back, The haven't removed the docs about this Effect [(IDCompositionFloodEffect - Microsoft Docs)](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/dn919732(v=vs.85))

I Inspected the dcomp.dll, and the `IDCompositionFloodEffect  `is still there, but there is no direct way to use it. Will it be possible to add it to direct N, or could you suggest any alternate method.

When I searched for GUID I get `949758ca-bc9c-4c51-907d-a12613639331`

![image](https://user-images.githubusercontent.com/72641365/129467280-841d5260-d416-4197-811a-ce87bce5fdd9.png)

**Comment by smourier** [comment]
Same story, you cannot use use the "old" Dcomp.dll (IDCompositionDevice1/2/3) for the acrylic brush (effect hierarchies), you must use WinRT's Windows.UI.Composition (for which you don't need DirectN). Both (old COM interface and new WinRT interfaces) are implemented by DComp.dll.

**Comment by Extrimis** [comment]
@smourier Thank you for Mentioning, i will look for another way using Windows.UI.Composition
