### ISSUE TITLE
Creating IDCompositionGaussianBlurEffect returns E_NOINTERFACE

### ISSUE THREAD

**Issue by Extrimis** [smourier/DirectN#13]
I have been trying to create blur Effect using `IDCompositionGaussianBlurEffect `but when i create the effect using `IDCompositionDevice3 `it throws exception with this message:

> System.InvalidCastException: 'No such interface supported (Exception from HRESULT: 0x80004002 (E_NOINTERFACE))'

Here is the code which throws the exception : 

`hr = dcompDevice3.Object.CreateGaussianBlurEffect(out var gauss);`

**Comment by smourier** [comment]
We're still working on the sample code. It's not ready yet.

You cannot use use the "old" Dcomp.dll (IDCompositionDevice1/2/3) for the acrylic brush (effect hierarchies), you must use WinRT's Windows.UI.Composition (for which you don't need DirectN).

**Comment by Extrimis** [comment]
I am trying to create mica support for Windows 8,8.1,10,11, so the WinRT API won't work with the DWM Private function that i use, if need to make it work i need to create an interop compositor to convert IDCompositionVisual to Windows.UI.Composition.Visual, and even though i use  Windows.UI.Composition.Visual it is only supported in Windows 10, so there is no backward compatibility.
