### ISSUE TITLE
error when create uwp app release package 

### ISSUE THREAD

**Issue by iloxmn** [smourier/DirectN#14]
InvalidCSharpIdentifierName

Severity	Code	Description	Project	File	Line	Suppression State
Error		MCG0037: MCG0037:InvalidCSharpIdentifierName Struct 'DirectN.HRESULT' in assembly 'Assembly(Name=DirectN, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null, Location=*\obj\x64\Release\ilc\in\DirectN.dll)' has a field with name '<Value>k__BackingField' that is invalid. This could be because the name is obfuscated or the field is auto-implemented by the compiler. Please make sure the field name follows C# identifier conventions.	

it's working in debug mode, but not release 
also I can't find a method to dispose items created, how can I destroy them from memory

**Comment by iloxmn** [comment]
Ok, but I can't find anything related to backingfield, so what do I need to do to make it work. 

Win2d provide a method to dispose font face, but I can't find it on other directwrite wrapper 
https://microsoft.github.io/Win2D/WinUI2/html/M_Microsoft_Graphics_Canvas_Text_CanvasFontFace_Dispose.htm

**Comment by smourier** [comment]
Don't use .NET native toolchain

**Comment by pjmlp** [comment]
@iloxmn Win2D is mostly written in C++.

**Comment by smourier** [comment]
closed due to inactivity
