### ISSUE TITLE
 Package DirectNCore 1.9.1 is not compatible with net5.0

### ISSUE THREAD

**Issue by viktoraskas** [smourier/DirectN#16]
Hi,

I have tried to add DirectNCore to my console app but getting this error:

Install-Package : NU1202: Package DirectNCore 1.9.1 is not compatible with net5.0 (.NETCoreApp,Version=v5.0). Package DirectNCore 1.9.1 supports: net5.0-windows8.0 (.NETCoreApp,Version=v5.0)

**Comment by smourier** [comment]
Hi,

Before you can install DirectNCore, you must update your csproj and make sure your use a TargetFramework element that is at least for Windows 8, so for example:

before:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
  </PropertyGroup>
  ...
</Project>

```

after:

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
  </PropertyGroup>
  ...
</Project>

```

**Comment by viktoraskas** [comment]
thanks
