### ISSUE TITLE
Code Generation Tool

### ISSUE THREAD

**Issue by diwot** [smourier/DirectN#2]
Hi, which tool did you use to automatically generate glue code? I would like to use Falcor (https://github.com/NVIDIAGameWorks/Falcor/tree/5a12f298c15b82297447906afafdcf5a2f58f99e) from C# because it makes using DirectX 12 more comfortable. But it might be more difficult to automatically generate a wrapper since Falcor uses object oriented coding style while DirectX seems to use more C like style. Great project this DirectN by the way!

**Comment by smourier** [comment]
Hi,

The tool that generates the file is a proprietary one, specially crafted for WindowsSDK-style COM interfaces and structures. So there's no way it could work on something like Falcor.

**Comment by semihartan** [comment]
Execuse me Simon, just wondered that  does the genereator you have make use of some kind of API specification format like IDL or smth else to generate those bindings/wrappers?

**Comment by smourier** [comment]
Hi,

The generator uses (an old version of) ClangSharp: https://github.com/dotnet/ClangSharp

And it parses all the "interesting" files (related to DirectX and other media-oriented technologies) that can be found in the Windows SDK (https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/), the .h, .idl, etc., that you can find in `C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0` for example.

**Comment by semihartan** [comment]
Hey, that's cool. Thank you for your answer.
