### ISSUE TITLE
DWriteCore interfaces

### ISSUE THREAD

**Issue by miquik** [smourier/DirectN#20]
Hi,
It would be possible to add C# interfaces of new DWriteCore API?

**Comment by smourier** [comment]
Hi,

I guess so, I've not looked at it yet, the Windows App SDK has just been release in version 1.0.
In fact, there may be other API from it to add.

I'll check that when I have some time.

**Comment by smourier** [comment]
Just a quick note: I've only seen a new function and a new enum value, all interfaces definitions seem the same.

**Comment by miquik** [comment]
Docs says dwrite_core.h define a symbol that “enables” some interfaces in dwrite3.h, I didn’t dig into yet
