### ISSUE TITLE
Registering remote font file loader

### ISSUE THREAD

**Issue by miquik** [smourier/DirectN#21]
Hi,
Sorry I'm here again with another problem. I follow this tutorial [creating-a-custom-font-set-using-known-remote-fonts-on-the-web](https://docs.microsoft.com/en-us/windows/win32/directwrite/custom-font-sets-win10#creating-a-custom-font-set-using-known-remote-fonts-on-the-web) and everything is working except one step. 
I successfully created an instance of IDWriteRemoteFontFileLoader (which inherit from IDWriteFontFileLoader), now i have to register it (step 4) using IDWriteFactory.RegisterFontFileLoader which require an IDWriteFontFileLoader as param. Should work if I pass the instance IDWriteRemoteFontFileLoader but, instead, I receive an invalid cast exception.

I don't know if I'm doing something wrong or there is a bug

Thanks

**Comment by smourier** [comment]
Hi,

Do you have any code to show? Also .NET's invalid cast exception can sometime find its origin in an underlying E_NOINTERFACE COM error, which can be a threading issue (not using an object in the same thread where it was created)

**Comment by miquik** [comment]
Here's my minimal code that reproduce that error
```
  using (var coref = DWriteFunctions.DWriteCreateFactory<IDWriteFactory7>())
  {
      hr = coref.Object.CreateHttpFontFileLoader(null, null, out IDWriteRemoteFontFileLoader newLoader);
      hr = coref.Object.RegisterFontFileLoader(newLoader);
      // do something
  }
```
This gives me invalid cast exception

**Comment by miquik** [comment]
Your workaround seems to work; at least I can execute RegisterFontFileLoader without exception. I also try IDWriteInMemoryFontFileLoader interface and it also works. Maybe there is some internal error in IDWriteRemoteFontFileLoader.
I ends up I have probably to implement my own custom RemoteFontLoader

Thanks
