### ISSUE TITLE
Missing function: MFEnumDeviceSources

### ISSUE THREAD

**Issue by Steph55** [smourier/DirectN#22]
Thank you for your great project! However, it seems to be missing an important function of Media Foundations: MFEnumDeviceSources

Is it possible to add it?

It also appears to me that the second parameter of IMFAttributes.GetAllocatorSTring() should be an [out] parameter, unless I don't understand something there...

Thanks!

**Comment by smourier** [comment]
Hi,

 IMFAttributes's GetAllocatedString() is defined as it should as the second parameter is marked as optional.
You must allocate it on the heap using Marshal methods.

But you don't need that, you can use the IMFAttributesExtensions class that has all needed helpers.
