### ISSUE TITLE
How to pass `System.Windows.Media.Imaging.BitmapSource` to `WicBitmapSource.FromSource()`

### ISSUE THREAD

**Issue by d2phap** [smourier/DirectN#28]
Hi, I'm playing around with this library on .NET 6
I use Magick.NET to read the image, then convert it to `System.Windows.Media.Imaging.BitmapSource`.

```cs
using var imgM = new MagickImage("photo.png");
System.Windows.Media.Imaging.BitmapSource src = imgM.ToBitmapSource();


using var bmp = WicBitmapSource.FromSource(src); // ERROR!

```

![image](https://user-images.githubusercontent.com/3154213/180764194-22cb0386-0233-45f1-a0fa-8092073fd98c.png)

Is there any way to convert `System.Windows.Media.Imaging.BitmapSource` to `WicNet.WicBitmapSource`?

**Comment by smourier** [comment]
Hi,

Aren't you confusing with this library : https://github.com/smourier/wicnet (if yes, can you delete this one and recreate the same over there)?

**Comment by d2phap** [comment]
Oh yeah, I was checking both repo! Created here: https://github.com/smourier/WicNet/issues/2
Thank you!
