### ISSUE TITLE
Thanks for building DirectN

### ISSUE THREAD

**Issue by stax76** [smourier/DirectN#3]
Hello,

I just want to say thanks. I've used DirectN in my app StaxRip (new version with DirectN not released yet).

I was getting an exception (read/write to protected memory) from ID2D1DeviceContext.GetSize. I believe the bug is in Direct2D and not in DirectN, I used then the size of the Win32 window instead. In my C++ prototype it was working fine, I've seen before that native code works and managed code produces read/write to protected memory exception.

https://github.com/staxrip/staxrip/blob/master/General/VideoRenderer.vb

**Comment by smourier** [comment]
Hi (Thanks!).

GetSize is on ID2D1RenderTarget (which ID2D1DeviceContext derives from). The definition look all right in .NET to me.

Hmmm that's strange. Is it x86 or x64? Do you see the full stack (like if you debug and disable "just my code" and enabled native debugging), how is the stack? Is it in Direct2D or in some .NET marshaling/interop layer?

Also, does GetPixelSize work?

Or do you have a way for me to reproduce?

**Comment by stax76** [comment]
It gives different exceptions:

x64:

System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'

x86:

System.Runtime.InteropServices.MarshalDirectiveException: 'Method's type signature is not Interop compatible.'

```C#
using System;
using System.Windows.Forms;

using DirectN;

namespace WindowsFormsApp1
{
    public partial class Form1 : Form
    {
        ComObject<ID2D1Factory> Factory;
        ID2D1HwndRenderTarget RenderTarget;
        ID2D1DeviceContext DeviceContext;

        public Form1()
        {
            InitializeComponent();
        }

        protected override void OnShown(EventArgs e)
        {
            base.OnShown(e);

            Factory = D2D1Functions.D2D1CreateFactory(D2D1_FACTORY_TYPE.D2D1_FACTORY_TYPE_SINGLE_THREADED);

            var hwnd_render_target_properties = new D2D1_HWND_RENDER_TARGET_PROPERTIES {
                hwnd = Handle, pixelSize = new D2D_SIZE_U(ClientSize.Width, ClientSize.Height)
            };

            var render_target_properties = new D2D1_RENDER_TARGET_PROPERTIES();

            Factory.Object.CreateHwndRenderTarget(
                ref render_target_properties,
                ref hwnd_render_target_properties,
                out RenderTarget).ThrowOnError();

            DeviceContext = RenderTarget as ID2D1DeviceContext;
            DeviceContext.GetSize();
        }
    }
}
```

**Comment by smourier** [comment]
Ok, so what happens is .NET cannot match the C side definition of some methods. In C the method is defined like this:

    STDMETHOD_(D2D1_SIZE_F, GetSize)() CONST PURE;

which means the return value is a D2D1_SIZE_F struct (not a pointer to it, but the struct itself).

In .NET, I have defined it like this:

        [PreserveSig]
        D2D_SIZE_F GetSize();
        
Which seems to match, but in fact, it doesn't... even with PreserveSig, I think this is due to the fact this struct size is 8 bytes long (it works fine with enums, etc.). The solution is to replace it by this:

        [PreserveSig]
        void GetSize(out D2D_SIZE_F size);

and it should work in x86 and x64.

I will have to modify the source. This construct is quite rare in COM, but it's probably present in other methods. In the mean time, you can continue testing if you get the C# definition and rewrite it, something like this:

    [Guid("2cd90694-12e2-11dc-9fed-001143a055f9"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public partial interface ID2D1RenderTargetFix : ID2D1Resource
    {
        // copy paste the rest
        
        [PreserveSig]
        void GetSize(out D2D_SIZE_F s);

        // copy paste the rest
    }

    [Guid("e8f7fe7a-191c-466d-ad95-975678bda998"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public partial interface ID2D1DeviceContextFix : ID2D1RenderTarget
    {
        // copy paste the rest
        
        [PreserveSig]
        new void GetSize(out D2D_SIZE_F s);

        // copy paste the rest
    }

and just cast the pointers into the fixed definitions:

    var rt = (ID2D1RenderTargetFix)renderTarget;

Sorry for that.

**Comment by stax76** [comment]
Thanks for investigating it, I don't really need to use this function, everything is fine.

**Comment by smourier** [comment]
I have updated the source and the nuget with modifications above.

**Comment by stax76** [comment]
Thanks for the support. I noticed that ID2D1RenderTarget in d2d1.h has more methods, it has 3 CreateSolidColorBrush overloads, DirectN ends after IsSupported(). I used a CreateSolidColorBrush extension method.

**Comment by smourier** [comment]
Yes, these are not PURE/abstract COM methods, they're just C/C++ helpers methods, so they can't be defined in the equivalent .NET COM interface.

They could be defined as .NET extension methods, that's somehow what I've done in the https://github.com/smourier/DirectN/tree/master/DirectN/DirectN/Extensions part, but it's not strictly equivalent, and it's far from being exhaustive (this section it's not generated by coded by hand).

**Comment by stax76** [comment]
Thanks for the explanation, my C++ and COM knowledge is rather basic.
