### ISSUE TITLE
Example for using a geometric mask to clip a region

### ISSUE THREAD

**Issue by d2phap** [smourier/DirectN#30]
Hi @smourier,

I'm following this tutorial: https://learn.microsoft.com/en-us/windows/win32/direct2d/how-to-clip-with-layers
to create an inverted rectangle for selection. But it does not work due to the `D2D1_LAYER_PARAMETERS` is not valid.

My code is as below:
```cs
var selection = new D2D_RECT_F(0, 0, 200, 100);
var rectGeo = _d2dFactory.CreateRectangleGeometry(selection);

var lp = new D2D1_LAYER_PARAMETERS()
{
  geometricMask = rectGeo.StructureToPtr(),
  maskAntialiasMode = D2D1_ANTIALIAS_MODE.D2D1_ANTIALIAS_MODE_PER_PRIMITIVE,
};

_renderTarget.BeginDraw();

_renderTarget.PushLayer(lp);
_renderTarget.DrawBitmap(...);
_renderTarget.FillRectangle(...);
_renderTarget.PopLayer();

_renderTarget.EndDraw();
```

And this is what I want to draw:

![image](https://user-images.githubusercontent.com/3154213/196694361-1b97531b-2953-4e6c-89c3-4cbb0a5209c4.png)

Thank you!

**Comment by smourier** [comment]
Hi,

If `_d2dFactory` is a `IComObject<ID2D1Factory1>` then, it's not a structure, but a wrapper on a COM object, so you can get an `IntPtr` (a COM reference pointer) from it with a code like this:

    var ptr = Marshal.GetIUnknownForObject(rectGeo.Object);

**Comment by d2phap** [comment]
Thank you! I forgot this 😅
