### ISSUE TITLE
How to draw multiple VertexBuffer data at the same time

### ISSUE THREAD

**Issue by Sam-aki** [smourier/DirectN#38]
First of all, let me apologize that this is not a DirectN Issue.
I am currently creating a project using DirectN and am having trouble getting some of it to work.
I would appreciate a helping hand if you would be so kind.
For more information, please see the [my question](https://stackoverflow.com/questions/76562493/how-to-draw-multiple-vertexbuffer-data-at-the-same-time-in-a-winui3-application) at stackoverflow.
i want to draw multiple vertexbuffers.

**Comment by smourier** [comment]
Hi,

I've taken a quick look but it doesn't really seem to be related to DirectN(Core).
Sorry, I'll have to close it ¯\_(ツ)_/¯  Hopefully, there are more people on StackOverflow than on this forum (including myself)
