### ISSUE TITLE
IDirect3DVertexBuffer9 Lock Usage

### ISSUE THREAD

**Issue by Revan1985** [smourier/DirectN#41]
Hello,
I need an help for using DirectN with Directx9.
I am using the IDirect3DVertexBuffer9 Lock method, but since this required an IntPtr, I am not able to understand how translate from c++ to c# code.
In c++ I am using this code

`VERTEX* vertices;
	HR(m_pVertexBuffer->Lock(0, 0, (void**)&vertices, D3DLOCK_DISCARD));
	::memcpy(vertices, vertexArray, sizeof(vertexArray));
	return m_pVertexBuffer->Unlock();`
while in c# should become something similar
`nint ppbData = nint.Zero;
        if ((hr = _vertexBuffer.Object.Lock(0, 0, ppbData, Constants.D3DLOCK_DISCARD)).IsError) { return hr; }
        var gc = GCHandle.Alloc(vertexArray, GCHandleType.Pinned);

        gc.Free();

        return _vertexBuffer.Object.Unlock();`
I don't understand if I am on right way, or is totally messed up.
How should I complete it?
I don't know if i need to "allocate" the lock ppbData, and in which way.

Thank you for any support.

**Comment by Revan1985** [comment]
Thank you, this is what i needed to know.
Thank you for your speedy answer 😃

**Comment by Revan1985** [comment]
Hello,
I am sorry, but i need to reopen this issue, just to not open a new one...
I am having a similar problem now.
I need to create pixel\vertex shaders, but signature for creation is this...
`new HRESULT CreatePixelShader(ref uint pFunction, out IDirect3DPixelShader9 ppShader);`
How can i use it? I was trying a similar way, cause i need to create the pixelbuffer from a ReadOnlySpan<byte>, but uint is not compatible with an intptr.
How can i load them (also from a different source, not only byte[] or similar source).

Thank you for your support, but the d3d9 wrapper is cryptical 😅

**Comment by smourier** [comment]
Hi,

This is not the same issue, next time please create a new question.

Anyway, it's again caused by legacy C headers for DirectX9. This is how is defined the method in d3d9.h

    STDMETHOD(CreatePixelShader)(THIS_ CONST DWORD* pFunction,IDirect3DPixelShader9** ppShader) PURE;

C# `ref int` seems equivalent, but `pFunction `is in fact an array so the header is indeed not sufficient to generate an equivalent C# code.

I've updated the code https://github.com/smourier/DirectN/commit/839cb42ee7b958cf3e1ab8284a58d34069dbb35c and published new nugets, and it's now generated in C# as 

    HRESULT CreatePixelShader(IntPtr pFunction, out IDirect3DPixelShader9 ppShader);

**Comment by Revan1985** [comment]
than you for your answer.
Yes, you have reason, I should have opened a new issue.
Anyway thank you for your patience and support.
