### ISSUE TITLE
Please add XMFLOAT2!  orz

### ISSUE THREAD

**Issue by vmx17** [smourier/DirectN#43]
Hi! How are you doing? Not issue but request (as usual). Title says all.  
Recently, I hit a question why DirectN does not support XMFLOAT2. I use XMFLOAT3 for position, XMFLOAT4 for color but what is for uv? It should not be `Rect` of `Windows.Foundation` nor `MF_FLOAT2` of `Windows.Win32...`.
Once I heard DirectXMath is not provided in dlls but you're providing XMFLOAT3 and 4, it is a lacking parts of plastic model kit, isn't it?
....
But!
Just I've hit an idea to use Vector2,3,4 from System.Numerics.

**Comment by smourier** [comment]
Hi,

I added XMFLOAT3 and 4 to support the sample (to mimic C++ code). They are just similar arrays of floats so you don't stricly need them, however, I have added XMFLOAT2 as it makes sense :-)

**Comment by vmx17** [comment]
I'd like to express my gratitude for it. I'll try it tommorow. What's the secret to make code so fast?
