### ISSUE TITLE
where is the Guid pixelFormat paramater define ?

### ISSUE THREAD

**Issue by sgf** [smourier/DirectN#49]
```C#
   public static IComObject<IWICBitmap> CreateBitmap(this IComObject<IWICImagingFactory> factory, int width, int height, Guid pixelFormat, WICBitmapCreateCacheOption option = WICBitmapCreateCacheOption.WICBitmapNoCache)
    {
        return (factory?.Object).CreateBitmap(width, height, pixelFormat, option);
    }

    public static IComObject<IWICBitmap> CreateBitmap(this IWICImagingFactory factory, int width, int height, Guid pixelFormat, WICBitmapCreateCacheOption option = WICBitmapCreateCacheOption.WICBitmapNoCache)
    {
        if (factory == null)
        {
            throw new ArgumentNullException("factory");
        }

        Guid pixelFormat2 = pixelFormat;
        factory.CreateBitmap((uint)width, (uint)height, ref pixelFormat2, option, out var ppIBitmap).ThrowOnError();
        return new ComObject<IWICBitmap>(ppIBitmap);
    }
```

i cant find the pixelFormat

**Comment by smourier** [comment]
DirectN has no intelligence, it exposes bindings for exising COM objects, here [IWICImagingFactory::CreateBitmap method](https://learn.microsoft.com/en-us/windows/win32/api/wincodec/nf-wincodec-iwicimagingfactory-createbitmap), so you need to go to official documentation to learn how it works.

[Native Pixel Formats Overview](https://learn.microsoft.com/en-us/windows/win32/wic/-wic-codec-native-pixel-formats)

Note in this case, DirectN also defines the pixel formats usable from .NET https://github.com/smourier/DirectN/blob/master/DirectN/DirectN/Extensions/WICConstants.cs

**Comment by sgf** [comment]
thank you very much
