### ISSUE TITLE
Incorrect pSrcData parameter type in D3DCompile function

### ISSUE THREAD

**Issue by gsuberland** [smourier/DirectN#5]
The [`D3DCompile` function](https://github.com/smourier/DirectN/blob/master/DirectN/DirectN/Generated/Functions.cs#L740) has the first parameter, `pSrcData`, defined as `IntPtr[]` with an  `LPArray` attribute, but the [official docs](https://docs.microsoft.com/en-us/windows/win32/api/d3dcompiler/nf-d3dcompiler-d3dcompile) define it as an `LPCVOID`. The `D3DCompile2` function is similarly affected.

This function takes either an ASCII string or a compiled effect, so I would expect that the parameter type should be `byte[]` with the same `LPArray` attribute as is currently used.

**Comment by smourier** [comment]
Hi,

Thanks for reporting this!

It's due to the fact these are quite old definitions so they don't have newer less ambiguous annotations.

Anyway, I will fix it ASAP. The parameter will be defined as IntPtr to be consistent with the rest of the definitions in face of this kind of type.

**Comment by gsuberland** [comment]
Thanks. IntPtr is fine, as it's easy to marshal this data into unmanaged memory anyway.

**Comment by smourier** [comment]
It should have been fixed by the latest commit.
