### ISSUE TITLE
Missing legacy DDraw/D3D functions

### ISSUE THREAD

**Issue by RibShark** [smourier/DirectN#54]
As of https://github.com/smourier/DirectN/commit/4c6c522a38b0da03f6dc79bcdfcea47508dc20e5, a lot of legacy functions such as `DirectDrawCreate` are missing. My use case for these is for creating configuration programs for old games that use these APIs. It would be nice to have these functions in DirectN so that I do not need to manually define them (the respective interfaces and such are already included in DirectN).

**Comment by smourier** [comment]
DirectDraw is clearly not a target, plus the problem with it is the SDK header files are very old (they are not annoted) so how interfaces are generated may not always be correct.

However, I've added 7 functions in this commit https://github.com/smourier/DirectN/commit/b564245135b6e12854a3431169fe03b802e4451c

You can see if you can work with it.
