### ISSUE TITLE
ID2D1DeviceContext SetTarget does not accept null

### ISSUE THREAD

**Issue by Telanor** [smourier/DirectN#58]
The extension method throws when attempting to pass null as the target, which is necessary to resize the swapchain.  I got around the issue by calling `.Object.SetTarget` directly but the check should probably be removed.

```
public static void SetTarget(this ID2D1DeviceContext context, ID2D1Image target)
{
	if (context == null)
	{
		throw new ArgumentNullException("context");
	}

	if (target == null)
	{
		throw new ArgumentNullException("context");
	}

	context.SetTarget(target);
}
```

**Comment by smourier** [comment]
Absolutely, thanks for reporting this, it's fixed in the source now https://github.com/smourier/DirectN/commit/1823415f17df5642978384e4977ef4710c2b27ae

**Comment by Telanor** [comment]
Thanks!
