### ISSUE TITLE
System.ComponentModel.Win32Exception  when set D2D1_STRAIGHTEN_PROP.D2D1_STRAIGHTEN_PROP_MAINTAIN_SIZE  in  Direct2DEffects.CLSID_D2D1Straighten

### ISSUE THREAD

**Issue by Charltsing** [smourier/DirectN#60]
System.ComponentModel.Win32Exception
  HResult=0x80004005
  Message=参数错误。
  Source=DirectNStandard
  StackTrace:
   在 DirectN.HRESULT.ThrowOnErrorExcept(IEnumerable`1 exceptedValues, Boolean throwOnError)

   在 DirectN.HRESULT.ThrowOnError(Boolean throwOnError)

   在 DirectN.ID2D1PropertiesExtensions.SetValue(ID2D1Properties properties, Int32 index, Object value)

   在 DirectN.ID2D1PropertiesExtensions.SetValue(IComObject`1 properties, Int32 index, Object value)

![捕获](https://github.com/smourier/DirectN/assets/19963715/99ef7635-7b3a-4f4f-935d-54721c06ab37)

DirectN 1.16.1

How should I set D2D1_STRAIGHTEN_PROP_MAINTAIN_SIZE parameters ?

**Comment by smourier** [comment]
Hi,

There's a small bug in extensions methods for boolean value, you can set it more directly like this:

false:

    fx.SetValue((int)D2D1_STRAIGHTEN_PROP.D2D1_STRAIGHTEN_PROP_MAINTAIN_SIZE,
        D2D1_PROPERTY_TYPE.D2D1_PROPERTY_TYPE_BOOL,
        BitConverter.GetBytes(0));

true:

    fx.SetValue((int)D2D1_STRAIGHTEN_PROP.D2D1_STRAIGHTEN_PROP_MAINTAIN_SIZE,
        D2D1_PROPERTY_TYPE.D2D1_PROPERTY_TYPE_BOOL,
        BitConverter.GetBytes(1));

**Comment by Charltsing** [comment]
Thanks for your reply.
I hope the bug will be fixed in future versions.

**Comment by smourier** [comment]
It should be fixed by latest commit https://github.com/smourier/DirectN/commit/46512bb160e0dfe5917c12974bc1fd147dac7191
