### ISSUE TITLE
How to use CLSID_D2D1Crop ? 

### ISSUE THREAD

**Issue by Charltsing** [smourier/DirectN#61]
![OEM](https://github.com/user-attachments/assets/fd57a25d-6fd1-4e70-aeb1-0c48becbd43a)

I try use D2D crop my image
https://learn.microsoft.com/en-us/windows/win32/direct2d/crop    ---> Microsoft documentation is incorrect ?

I try the following code :  crop form(0,0) to (238,325)
```
using IComObject<ID2D1Effect> effect = Device.CreateEffect(Direct2DEffects.CLSID_D2D1Crop);
effect.SetInput(D2D1Bitmap, 0);

D2D_VECTOR_4F rectf = new(0, 0, 238, 325);   
effect.SetValue((int)D2D1_CROP_PROP.D2D1_CROP_PROP_RECT, rectf);
```
**it work fine.**

then i modify x = 50,y=50, i try to crop from(50,50) to (238,325)
i set D2D_VECTOR_4F rectf = new(50, 50, 238, 325);   **it is Incorrect cropping(image move to (50,50), croped image width is 188,height is 275**
![o1](https://github.com/user-attachments/assets/6cb83e69-8d83-49fd-8b65-8c028b81ebad)
The background is transparent

i try D2D_VECTOR_4F rectf = new(50, 50, 238-50, 325-50);   **it crop correctly (image move to (50,50), croped image width is 138,height is 225**
![o2](https://github.com/user-attachments/assets/9822acc8-b816-43c2-800d-430cefc93a44)
The background is transparent

Did I do something wrong?
How to crop image by CLSID_D2D1Crop?

**Comment by smourier** [comment]
I don't think you're doing anything wrong

For D2D_VECTOR_4F, x and y are a first point coordinates, z and w are a second point coordinates, both points define a rectangle and the crop zone is this rectangle, so (50, 50, 238, 325) will indeed be 238-50 => 188 width as explained in documentation https://learn.microsoft.com/en-us/windows/win32/direct2d/crop#output-bitmap

As for the output, it depends on how you use it. If you use output = ID2D1Effect::GetOutput and img = ID2D1DeviceContext::GetImageLocalBounds(output), you'll see it has the size that was asked (there's no concept of transparency in the effect itself).

PS: this is all Direct2D related, not DirectN related

**Comment by Charltsing** [comment]
What I mean is that CLSIDD_2D1Cop does not implement cropping images from specified coordinates (50,50), it first moves the image and then crops it

![33](https://github.com/user-attachments/assets/4770ca08-605c-4efa-b641-cc0817fcf55b)

Is this a problem with Microsoft Direct2D?

**Comment by smourier** [comment]
Like I said D2D1Effect::GetOutput will get you the resulting image which corresponds exactly to the rectangle you asked for,including the fact it will be x,y translated. The result you get is because you output it as is.

**Comment by Charltsing** [comment]
I found the problem was with drawimage
thank for your help. 

By the way, when will the latest version be released?

**Comment by smourier** [comment]
I've just done it
