### ISSUE TITLE
Drawing by DirectWrite and ResizeBuffers function of swapchain

### ISSUE THREAD

**Issue by 468samejima** [smourier/DirectN#63]
Hello!
This is a trouble I had when I added DirectWrite and modified the screen resizing process to DirectN's WinUI sample.
First, regarding the screen resizing process, the resizing process was originally the following process
```
        private void OnSizeChanged(object sender, SizeChangedEventArgs e)
        {
            Dispose();
            Init();
        }
```
In contrast, I succeeded in reducing the time required for processing by executing `ResizeBuffers()` on the object of `IComObject<IDXGISwapChain1>`. (This is working on [this commit]( https://github.com/468samejima/testDWrite/commit/66d2ace9896e60118658b20fdac5c9197b7b15d5))

Next, I added a DirectWrite character drawing process to this sample.
Basically, the processing necessary for DirectWrite exists in `internal class RendererDirectWrite` and is called in the following places in MainWindow.Xaml.cs.
- `OnSizeChanged(object sender, SizeChangedEventArgs e)`(line:134)
- `Init()`(line:322)
- `Render(object sender, object e)`(line:383)

However, when the window is resized after these two updates are made, the size of the drawing area does not accompany the resizing of the window.(on [this commit](https://github.com/468samejima/testDWrite/commit/61f1aa8cfafcc7a595d6239abe0caf26e3f7c2d9))

This may not be a DirectN problem since `ResizeBuffers` is a function on Objects.
However, `_swapChain.ResizeBuffers(~)` does not work well for `IComObject<IDXGISwapChain1> _swapChain`, so this is the way I did it.
If you have a solution, please let me know.

**Comment by smourier** [comment]
Hi,

Not sure about the problem you have but indeed, DirectN is merely a wrapper over (lots of) other technologies such as Direct Write.

I'm not generally supporting problem on these technologies, only supporting issues with the DirectN classes themselves, ie: errors with .NET => native bindings essentially.

AFAIK, ResizeBuffers is defined ok, and DirectWrite interop works ok too (it's used in this project https://github.com/aelyo-softworks/Wice here for example https://github.com/aelyo-softworks/Wice/blob/main/Wice/TextBox.cs).

So, I can't help you with that, and your sample code is significantly modified and complex. I could try to help with a smaller sampler that clearly pinpoint a specific issue.

**Comment by 468samejima** [comment]
Thanks for your response!
The problem of an exception occurring when processing the resizebuffers function of swapchain has been resolved.
The problem was simply that there were not enough resources to be released on the DirectWrite side.
I'm leaving the [source](https://github.com/468samejima/testDWrite/commit/bf2afc3750a380efd0f7ddfbd6a77f0cf3d8b296) in case someone else encounters the same problem.
Please close the issue. Thank you very much.
