### ISSUE TITLE
IInkD2DRenderer Example

### ISSUE THREAD

**Issue by adstep** [smourier/DirectN#65]
Do you have any examples of using IInkD2DRenderer.Draw?

I'm having trouble passing a pointer to an iterable of inkstrokes without it throwing a casting exception.

**Comment by smourier** [comment]
No, but it's C# definition seems correct with regards to it's native one:

    [ComImport, Guid("407fb1de-f85a-4150-97cf-b7fb274fb4f8"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface IInkD2DRenderer
    {
        [PreserveSig]
        HRESULT Draw([MarshalAs(UnmanagedType.IUnknown)] object pD2D1DeviceContext, [MarshalAs(UnmanagedType.IUnknown)] object pInkStrokeIterable, bool fHighContrast);
    }


    MIDL_INTERFACE("407fb1de-f85a-4150-97cf-b7fb274fb4f8")
    IInkD2DRenderer : public IUnknown
    {
    public:
        virtual HRESULT STDMETHODCALLTYPE Draw( 
            /* [in] */ __RPC__in_opt IUnknown *pD2D1DeviceContext,
            /* [in] */ __RPC__in_opt IUnknown *pInkStrokeIterable,
            /* [in] */ BOOL fHighContrast) = 0;
        
    };

**Comment by adstep** [comment]
I'm trying something like:

```csharp
[ComImport]
[Guid("4044e60c-7b01-4671-a97c-04e0210a07a5")]
public class InkD2DRenderer
{
}

IComObject<ID2D1DeviceContext> context = ...;

var rendererObj = new InkD2DRenderer();
var strokes = new List<InkStroke>();

var renderer = rendererObj.As<IInkD2DRenderer>();

renderer.Draw(context.Object, strokes, false);
```

Which results in: 
```
System.InvalidCastException: Specified cast is not valid.
```

Is it complaining about the List I'm passing? What can I pass as the structure containing the strokes?

**Comment by smourier** [comment]
You certainly cannot pass a .NET List as is, it's not a COM object. The system expects an iterable, ie: `Windows::Foundation::Collections::IIterable<InkStroke>`. DirectN has no facility for that, and AFAIK, C#/WinRT hasn't either, it only does the `IIterable<T>` => C# `IIEnumerable<T>` as a consumer.

**Comment by adstep** [comment]
If I create an `Windows.UI.Input.Inking.InkStrokeContainer`, would that be expected to internally manage the strokes using something that does implement IIterable? 

It exposes a method to `GetStrokes` which returns an `IReadOnlyList<InkStroke>`. 

The returned object is a `WinRT.ObjectReference<ABI.System.Collections.Generic.IEnumerable<Windows.UI.Input.Inking.InkStrok>>`.

Looking in cswinrt it seems like this should be an `IIterable<T>`:
```
    [DynamicInterfaceCastableImplementation]
    [Guid("FAA585EA-6214-4217-AFDA-7F46DE5869B3")]
#pragma warning disable CA2256 // Not implementing IIterable<T> for [DynamicInterfaceCastableImplementation], as we don't expect to need IDIC for WinRT types
    internal interface IIterable<T> : ABI.System.Collections.Generic.IEnumerable<T>
#pragma warning restore CA2256
    {
        public static new Guid PIID = ABI.System.Collections.Generic.IEnumerableMethods<T>.PIID;
    }
```

**Comment by smourier** [comment]
If you post a fully reproducing sample, I'll try to see what I can do

**Comment by adstep** [comment]
I created a repo with a test to exercise what I'm trying to do. But I'm getting a different error now that makes more sense.

The error I'm getting is E_NO_INTERFACE. I looked at the vtable for the instantiated InkD2DRenderer and it only shows as having 3 methods. Looking at other people's implementation of IInkD2DRenderer it seems like Draw should be the 4th method in the vtable. I'm not sure if I'm instantiating the object incorrectly or maybe it's not supported in WinUI3?

As this doesn't seem like a DirectN issue so feel free to close. But would appreciate any tips given your expertise.

https://github.com/adstep/ink-renderer-demo/blob/a7d22c0d80b677838a03281a0d8cebece61ba1ba/src/InkRendererDemo/InkRendererDemo/UnitTests.cs#L10-L32

**Comment by smourier** [comment]
`InvalidCastException` is the exact .NET transation of `E_NOINTERFACE` when talking COM.

What happens when you do this:

    var inkStrokeContainer = new InkStrokeContainer();
    var strokes = inkStrokeContainer.GetStrokes();

is C#/WinRT wraps everything with nice .NET collection objects, so `strokes `is a pure .NET object that you cannot use as a COM object that would implement something useful.

Once solution is to redeclare `IInkStrokeContainer` and use it yourself, something like this:

    [ComImport, InterfaceType(ComInterfaceType.InterfaceIsIUnknown), Guid("22accbc6-faa9-4f14-b68c-f6cee670ae16")]
    public interface MyIInkStrokeContainer
    {
        void _VtblGap0_15(); // skip 3 (IInspectable) + 12 methods

        [return: MarshalAs(UnmanagedType.IUnknown)]
        object GetStrokes();
    }

    var inkStrokeContainer = new InkStrokeContainer();

    var c = inkStrokeContainer.As<MyIInkStrokeContainer>();
    var strokes = c.GetStrokes();

    renderer.Draw(d2D1DeviceContext.Object, strokes, false).ThrowOnError();

**Comment by adstep** [comment]
OK thanks that works! Too bad there isn't support for converting C# collections to something that supports IIterable.
