### ISSUE TITLE
Can you please add DirectMusic?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [smourier/DirectN#67]
Hello,

I've seen that in your https://github.com/smourier/DirectNAot project you've made available all the classes to access [DirectMusic](https://github.com/smourier/DirectNAot/blob/master/DirectN/Generated/DirectN/IDirectMusic.cs), but since there yet no nuget packages available, I wonder if you could add it to this one in the meantime. I am working on a new project that requires those bindings to get the [`guidPort`](https://learn.microsoft.com/en-us/previous-versions/ms808239(v=msdn.10)) out of a MIDI device and your library is the closest I could find to allow me to use the native [`IDirectMusic8::EnumPort`](https://learn.microsoft.com/en-us/previous-versions/ms808935(v=msdn.10)) API.

Thank you in advance in the meantime for the great work you're doing on this project.

Best regards,
Julian

**Comment by julianxhokaxhiu** [comment]
I was able to solve this myself using [CsWin32](https://github.com/microsoft/cswin32), however I think it would still be a nice addition to your library. However no time pressure or anything. Thanks nevertheless :)

**Comment by smourier** [comment]
Hi,

This should have been brought by the latest commit: https://github.com/smourier/DirectN/commit/22563544a00213083d1d2cacf2545d5b24fa5199

**Comment by julianxhokaxhiu** [comment]
That was fast! Thanks a lot, I'll give it a shot as soon as I can and let you know. Appreciated.
