### ISSUE TITLE
MFCreateSensorGroup not found entry point

### ISSUE THREAD

**Issue by oven425** [smourier/DirectN#69]
```c#
var hr = DirectN.Functions.MFCreateSensorGroup("SymbolLink", out var group);
```
excrption:
Unable to find an entry point named 'MFCreateSensorGroup' in DLL 'mfplat'. 

maybe refrence [this](https://learn.microsoft.com/zh-tw/uwp/win32-and-com/win32-apis)

**Comment by smourier** [comment]
Indeed, Media Foundation is composed of many dlls and the generator was missing some imports. This has been fixed with latest commit https://github.com/smourier/DirectN/commit/5eeb290be0d912bb1f697de8868513a7b60035fb
