### ISSUE TITLE
Setting swap chain on WinUI 3.0 SwapChainPanel

### ISSUE THREAD

**Issue by TGRye** [smourier/DirectN#8]
I'm trying to set the swap chain on a WinUI 3.0 Xaml SwapChainPanel but cannot find a way to do this using C#/DirectN. (perhaps there isnt one and C++ is required??)

```
    public class D3D11Panel : SwapChainPanel, IDisposable
    {
    ....
    void Init()
    {
        //Create device and swap chain....
        ....
        ....
        _swapChain = fac.CreateSwapChainForComposition<IDXGISwapChain1>(DXGIDev, desc);
        SwapChainPanel mypanel = this;
            
        var sc = _swapChain.Object.As<IDXGISwapChain>();
        SwapChainPanel mypanel = this;
        var nativepanel = mypanel.As<ISwapChainPanelNative>();     //<<<<< EXCEPTION THROWN HERE
        nativepanel.SetSwapChain(sc);
```
> System.InvalidCastException: 'Invalid cast from 'WinRT.IInspectable' to 'DirectN.ISwapChainPanelNative'.'

I cant figure out how to cast my SwapChainPanel to a DirectN.ISwapChainPanelNative. I'm really not familiar with WinRT or ComObjects and I was hoping to avoid having to dive into C++ / interop. I tried to create a DirectN.ComObject<> in various ways but cant get anything to work. (many hours trying)
Any help would be much appreciated.

**Comment by smourier** [comment]
Hi,

In general, you shouldn't need C++.

Are you using .NET Framework or .NET Core (3-5+?) Microsoft has changed lots of things about COM interop between .NET Framework and .NET Core.

Can you try to redefine manually ISwapChainPanelNative to add ComImport to it? This is typically something that has changed with .NET 5 (it was never needed with .NET framework on COM interfaces...), so something like this:

    [ComImport, Guid("f92f19d2-3ade-45a6-a20c-f6f1ea90554b"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public partial interface ISwapChainPanelNative
    {
        [PreserveSig]
        HRESULT SetSwapChain(/* [annotation][in] _In_ */ IDXGISwapChain swapChain);
    }

you can also try a simple cast (but I'm not sure it's ok):

    var nativepanel = mypanel as ISwapChainPanelNative;
    var nativepanel = ((object)mypanel) as ISwapChainPanelNative;

I can't test by myself but if you have a small reproducing project, even if does nothing but that I can use to validate things, I can have a look at it.

**Comment by TGRye** [comment]
I'm targeting .Net 5 and using WinUI 3.0/ Reunion 0.5 for the UI. 
The simple cast doesnt work.

The ComImport code throws..
```
            _swapChain = fac.CreateSwapChainForComposition<IDXGISwapChain1>(DXGIDev, desc);

            SwapChainPanel mypanel = this;
            var nativepanel = mypanel.As<ISwapChainPanelNative>();  //<<<< Exception thrown here.
            nativepanel.SetSwapChain(_swapChain.Object);
```

>System.InvalidCastException: 'Element not found.'

Perhaps I'm doing it incorrectly. I did read that Net Framework to net Core changed a lot of things, but I've never touched COM stuff before. 

Here is the project..
[DirectNXAML.zip](https://github.com/smourier/DirectN/files/6302244/DirectNXAML.zip)

**Comment by smourier** [comment]
Ok, what happens is `ISwapChainPanelNative `from DirectN corresponds to this: https://docs.microsoft.com/en-us/windows/win32/api/windows.ui.xaml.media.dxinterop/nn-windows-ui-xaml-media-dxinterop-iswapchainpanelnative, note the `windows.ui.xaml.media.dxinterop.h` header file while in WinUI3, you must use the `ISwapChainPanelNative `from `microsoft.ui.xaml.media.dxinterop.h` it's a different interface and has a different IID, so you must redefine it like this:

    [ComImport, Guid("63aad0b8-7c24-40ff-85a8-640d944cc325"), InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
    public interface ISwapChainPanelNative
    {
        [PreserveSig]
        HRESULT SetSwapChain(IDXGISwapChain swapChain);
    }

And use it as usual:

    var nativepanel = mypanel.As<ISwapChainPanelNative>();


PS: you should use DirectNCore instead of DirectN for .NET core and .NET 5+ projects: https://www.nuget.org/packages/DirectNCore/

**Comment by TGRye** [comment]
That appears to have done it, or at least, it seems to have been accepted. I've changed to the Core version too. 

I am initially trying to replicate the DirectN.MinimalD3D11 example. 
I now get an exception thrown in the Render() method.

```
            _deviceContext.Object.ClearRenderTargetView(_renderTargetView.Object, backgroundColor);
```

>Exception thrown: 'System.InvalidCastException' in System.Private.CoreLib.dll
An exception of type 'System.InvalidCastException' occurred in System.Private.CoreLib.dll but was not handled in user code
Unable to cast COM object of type 'System.__ComObject' to interface type 'DirectN.ID3D11DeviceContext'. This operation failed because the QueryInterface call on the COM component for the interface with IID '{C0BFA96C-E089-44FB-8EAF-26F8796190DA}' failed due to the following error: No such interface supported (0x80004002 (E_NOINTERFACE)).

Many thanks for the help!

**Comment by smourier** [comment]
E_NOINTERFACE is often a threading issue. Make sure you call your DirectX objects on the same thread that created it. It appears with WinUI 3 it would be something like this:

    _= DispatcherQueue?.TryEnqueue(Render);

**Comment by TGRye** [comment]
Ahh, yeah. I was under the impression that this wasnt neccessary. 

```
_ticker = new VerticalBlankTicker();
            _ticker.Tick += (s, e) =>
            {
                DispatcherQueue?.TryEnqueue(
                    () =>
                    {
                        Render();
                    }
                    );
                
            };
            _ticker.Start();
```

This allows rendering to occur, but it ends up making the UI unresponsive. At least it shows that rendering is happening and that DirectN inside WinUI 3.0 is possible and in pure c#. I'll close the issue. 

I'll give an update later if/when I get a nicely functioning D3D11 panel that updates and resizes.
Many thanks for your help and for the library.

**Comment by TGRye** [comment]
There is a single line in the MS documentation on dx xaml interop that states...
> If you need to synchronize the updates of SwapChainPanel to those of the XAML framework, register for the Windows::UI::Xaml::Media::CompositionTarget::Rendering event

So if you subscribe to that event and call Render and Present(0,0), everything works great.

I have found another problem i cant seem to fix though. I am using multiple pages within a NavigationView. One page has my  D3D11Panel, another page has a button that calls DirectN.DXGIFunctions.DXGIReportLiveObjects(); 
I have also implemented IDisposable on my D3D11Panel, and make a call to Dispose() when you navigate to a different page. The goal is to clean up the DX objects when you leave the page.

 ```        
        private void Dispose(bool disposing)
        {
                ....
                SwapChainPanel mypanel = this;
                var nativepanel = mypanel.As<ISwapChainPanelNative>();
                nativepanel.SetSwapChain(null);

                _deviceContext?.Object.OMSetRenderTargets(0, null, null);
                _deviceContext?.Object.ClearState();
                _deviceContext?.Dispose();               
                _deviceContext = null;
                _swapChain.Object?.GetDevice1().Dispose();
                _swapChain?.Dispose();
                _swapChain = null;
                _renderTargetView?.Dispose();                
                _renderTargetView = null;
```

The issue is that if i load the page with the panel, it creates the DX objects, and if you then go to the page with the button and report the live objects, it shows there are still some live objects. If you go back to the DX page, it creates another set, leaving and reporting again will show twice the number of live objects. Essentially a memory leak, the more you navigate from and to the DX page the more live objects there are left over.

After commenting out various bits of the Init() function, i narrowed it down to this line...
```            
            nativepanel.SetSwapChain(_swapChain.Object); 
```
If this line is commented out, everything is cleaned up nicely as you navigate between pages.
Any ideas how to clean this up? I cant find anything about cleaning up the ISwapChainPanelNative and from what I can tell, there is nothing else in that interface.

**Comment by smourier** [comment]
Yes, usually with DirectX you'll never have like 1 object leak, but a lot because it's a full hierarchy of objects hold behind one root object.

So, SetSwapChain adds 1 reference to the the swapchain object will in turn adds an indirect reference to all other linked objects.

I guess the added reference is killed when the SwapChainPanel instance is itself GC collected. Not sure when that's supposed to happen. Have you check if there are SwapChainPanel still there in memory? Have you tried to call GC.Collect to see if it frees these (and by cascade your native swapchain reference)?

**Comment by TGRye** [comment]
I just used a bunch of WeakReferences for testing and did a load of testing but couldnt get it to clean up properly. It seems extending the swapchainpanel class is the problem. Testing showed that extending any control class would result in the new control not being cleaned up. 

I then reworked the code so that the D3D stuff is in a separate class to which you provide a SwapChainPanel. This works. The Renderer object is cleaned up. The SwapChainPanel is cleaned up, but the page stays, which i think will be due to the navigation system of the NavigationView. 
The important thing is that when you navigate away from the page, the D3D is all cleared up so is it working cleanly now.

**Comment by TGRye** [comment]
Okay, I think I'm done with this sample now. Most of the code was taken from the MinimalD3D11 sample, but the differences are pretty important and took some figuring out.

![DirectNXaml](https://user-images.githubusercontent.com/7727455/115382022-186b0800-a1cc-11eb-823c-094f601fce3f.png)

It currently renders on the XAML UI thread. I might investigate rendering on a different thread, but for my purposes I think its okay as is. 

Here is the source code for anyone who comes across this.. worth adding to the repo?
[DirectNXAML.zip](https://github.com/smourier/DirectN/files/6342893/DirectNXAML.zip)

@smourier Many thanks for your help. I'll be using this in a new project to display scientific data and I'm pretty excited by what this will let me do.

**Comment by smourier** [comment]
Thanks for sharing that :-)

I'm waiting for WinUI3 to be more stable and to be able to run it w/o that (painful) packaging thing, but that's a good idea. I'll keep that in mind.

PS: interestingly, the GPU is used ~2x more with this sample than with the original minimal one. Don't know why.

**Comment by jvanlangen** [comment]
Too bad, I get an error trying to load the projectfile: 

---------------------------
Microsoft Visual Studio
---------------------------
A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "" instead of a number, in condition "'$(TargetPlatformVersion)' >= '10.0.11000.0'".  C:\Users\jeroen\.nuget\packages\microsoft.projectreunion.foundation\0.5.0\build\Microsoft.ApplicationModel.Resources.PriGen.targets
---------------------------
OK   
---------------------------

**Comment by smourier** [comment]
Hi, this issue is close, please create another one and explain your problem in detail.

**Comment by smourier** [comment]
Note there's a now a new sample in the DirectN repo: [WinUI3 .NET 6 - Direct3D11 minimal sample](https://github.com/smourier/DirectN/tree/master/DirectN/DirectN.WinUI3.MinimalD3D11) that demonstrates how to use WinUI3 and a SwapChainPanel.
